### ISSUE TITLE
不能在運行VPN的情況下使用

### ISSUE THREAD

**Issue by yungyuan** [broh7995/swag_video_backup_downloader#2]
如果在運行VPN的時候會出現下面的error msg:

Verifying Swag token...
Traceback (most recent call last):
  File "publicDownloader.py", line 141, in <module>
  File "publicDownloader.py", line 21, in main
  File "swag_dl.py", line 23, in __init__
  File "swag_dl.py", line 51, in tokenValidationCheck
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 500, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 997, in _create
ValueError: check_hostname requires server_hostname
[154504] Failed to execute script 'publicDownloader' due to unhandled exception!

關閉VPN就可以正常使用了

**Comment by yungyuan** [comment]
我之前有做一個版本在mac環境透過 script 和 youtube-dl 來做的, 有機會和您一起完善影片功能嗎?

**Comment by broh7995** [comment]
> 

想問下是用甚麼語言寫的? 我有在考慮用go來寫看看
需要有跨平台運行的build
